### PR TITLE
Added callback option & return Promise from debounced function

### PR DESCRIPTION
**Pull request by sanduluca**
Added callback option & return Promise from debounced function
it is called when `originalFunction` is debounced and recives as first parameter returned data from `originalFunction`

### CODE REVIEW

**Comment by sanduluca** [comment]
@chodorowicz can you review my code and check if everything fits ok ?

**Comment by chodorowicz** [comment]
Hey @sanduluca! 
Thanks for your proposal. Before we proceed could you describe a use case for both of these features: returning a promise and adding a callback? Are those separate use cases or is the same one for both features?

**Comment by sanduluca** [comment]
As you requested in this issue #13 , I return Promise from debounced function. I don't see why returning Promise should be an option. Callback was added as an option, because somebody might like cb more than Promises.
When returning a Promie, you get a chance to await for it 😂. That's not the purpose of debounce function, but..

**Comment by chodorowicz** [comment]
This was not really really requested,  the #13 states that it should be considered ;) 
But still, it can be useful. But it would need to work in such way that subsequent promises returned by calling the debounced function should resolve. With your solution only the latest one resolves.

Consider this:
```ts
function f(n: number) {
  return n;
}
const df = debounce(f);
const p1 = df(1);
const p2 = df(2);
p1.then((x) => console.log("p1 is resolved", x)); // never resolved
p2.then((x) => console.log("p2 is resolved", x)); // this one resolves
```

A list of resolve functions would need to be kept and then all of them would need to be resolved. 
Let me know what do you think

As to callback, I'd keep it out the scope of this MR and consider it in another issue.

**Comment by sanduluca** [comment]
`debounce` delays values emitted by the source Observable, BUT drops previous pending delayed emissions if a new value arrives on the source Observable. 
That being said, all previous returned promises, will be dropped, if `waitMilliseconds` did not passes.
Thats the idea of `debounce` as I understand, so I don't see why `p1 should be resolved`

**Comment by chodorowicz** [comment]
We're working here with promises, not observables, so there won't be 1 to 1 mapping between this implementation and observable version od debounce.

I don't think there's a definition anywhere of what should debounce return and how this something should behave. 
If you look at some implementation of debounce, you can see that those promises are resolved and are not left forever in pending state.

- https://github.com/sindresorhus/p-debounce
- https://github.com/bjoerge/debounce-promise

I was also asking about your use case, because it'd be easier to determine which behaviour fits better.

**Comment by sanduluca** [comment]
Ok, now It resolves all promises returned by calling the debounced function.

Now got a question. What do we do, when debounced function is cancel
```javascript
function f(n: number) {
    return n;
}
const df = debounce(f);
const p1 = df(1);
const p2 = df(2);
p1.then((x) => console.log("p1 is resolved", x));
p2.then((x) => console.log("p2 is resolved", x));
df.cancel()
```
The are 4 options:
1. None of the promises are resolved. They stay in pending forever. (As it is now)
2. All promises are resolved with `undefined`
3. All promises are rejected
4. All promises are resolved with data provided as parameter to cancel function

**Comment by chodorowicz** [comment]
Cool, nice! 👏

So as to cancelling, that's a very good question. I'd say that rejecting them would make most sense.
If we thing of those promises resolving after the postponed `f` function is finally called (resolving with the return value of `f`), then if `f` is cancelled then I'd expect those promised to bo rejected.
That means that we would need to keep another list of `reject`, to call them in case of cancellation.

What do you think?

**Comment by sanduluca** [comment]
Cancellation of debounce function can represent a problem that a developer anticipated and want to handle.
Rejecting all promises, makes most sense for me, too, especially when a cancellation reason can be provided now 😀

**Comment by chodorowicz** [comment]
Nice, good stuff 👏 
We have still some problem with the tests. They always succeed as to the value promises resolve with.
You can see this by e.g. changing the the function `f` to  `const func = () => false;` and the test will be still green.
Because we're testing Promises and use timeouts we need to use [async Jest patterns](https://jestjs.io/docs/en/asynchronous.html)
I'd do this like this

```ts
test("it properly debounces function and returns a Promise", async () => {
  const func = () => 12345;
  const debouncedFunction = debounce(func, 100);

  const result = debouncedFunction();
  const result1 = debouncedFunction();
  jest.advanceTimersByTime(100);
  await Promise.all([result, result1]);

  expect(result).resolves.toEqual(12345)
  expect(result1).resolves.toEqual(12345)
});
```

**Comment by sanduluca** [comment]
> Nice, good stuff 👏
> We have still some problem with the tests. They always succeed as to the value promises resolve with.
> You can see this by e.g. changing the the function `f` to `const func = () => false;` and the test will be still green.
> Because we're testing Promises and use timeouts we need to use [async Jest patterns](https://jestjs.io/docs/en/asynchronous.html)
> I'd do this like this
> 
> ```ts
> test("it properly debounces function and returns a Promise", async () => {
>   const func = () => 12345;
>   const debouncedFunction = debounce(func, 100);
> 
>   const result = debouncedFunction();
>   const result1 = debouncedFunction();
>   jest.advanceTimersByTime(100);
>   await Promise.all([result, result1]);
> 
>   expect(result).resolves.toEqual(12345)
>   expect(result1).resolves.toEqual(12345)
> });
> ```

Ohh, sorry. Don't have much experience with jest and testing.
You was right. The test ends before Promise resolves.

**Comment by chodorowicz** [comment]
Thanks a lot for your contribution! 🙇 👏  I've released it with v3. I've improved also async tests a bit after I've merged the changes into master.

**Pull request merged**
