### PR TITLE
improve github actions config

### PR DESCRIPTION
**Pull request by chodorowicz**

### CODE REVIEW

**Comment by tony** [comment]
@chodorowicz This PR is a branch of your repository via [`push`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push).  It runs even without you make a pull request.

image


When I make a PR, like #44, it's a branch of my own repository, so it won't trigger without the [`pull_request`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) event being added to `on:` ([link](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories))

> When you create a pull request from a forked repository to the base repository, GitHub sends the `pull_request` event to the base repository and no pull request events occur on the forked repository.

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by tony** [comment]
Btw sorry if I went overboard on the explanation : GitHub Actions still confuse me!

**Comment by chodorowicz** [comment]
Thanks for the explanations and taking time to write them! 🙂 What confuses me still is that I had recently PRs from other cloned repos  and they had those CI build & checks running.
I've added this additional trigger `on: [push, pull_request]` but now as you can see there are two exactly the same builds running.
image

**Comment by tony** [comment]
@chodorowicz 

This is with a branch from your own repo right?

Try something like this:

```
on: [push, pull_request]

jobs:
  build:
    # Don't run twice for internal PRs from our own repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
```

**Comment by tony** [comment]
@chodorowicz Since master doesn't have even the earlier change (e.g. just the `on: [push, pull_request]`) I'm not able to make a pull request to try the behavior  w/ a PR from outside the repo

the changes only stick if master has the yml

**Comment by chodorowicz** [comment]
Nice, clever trick with his comparison of repository names. I've looked at the docs and some threads an I think this should config should be appropriate. So, we run builds on all PR actions against the main branch and push events on the main branch. This config [was mentioned here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push)

```
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

**Pull request merged**
