### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tony**

### CODE REVIEW

**Comment by chodorowicz** [comment]
Hey! thanks for PR with a typo fix. There seems to be some problem with the CI build. Can you re-trigger the build. E.g. by `git commit --amend --no-edit` and pushing it again?

**Comment by tony** [comment]
@chodorowicz Perhaps CI is broke.

https://github.com/chodorowicz/ts-debounce/blob/master/.github/workflows/nodejs.yml looks fine.

**Comment by tony** [comment]
I'm stumped.

**Comment by chodorowicz** [comment]
I've created an exactly the same PR and the status was green, CI checks have passed. So I'm stumped too 😄 
I've merged your PR anyway. Maybe it was some strange one-off infrastructure issue, not worth to research it too much. 
Thanks for the typo fix!

**Comment by tony** [comment]
Sounds good @chodorowicz ! And thank you for the project!

**Pull request merged**
