### PR TITLE
Improve type inference

### PR DESCRIPTION
**Pull request by karol-majewski**
It will allow type checking and IntelliSense.

```ts
const tardy = debounce(console.log, 1000)
tardy("Hello, Jakub");
```

image

### CODE REVIEW

**Comment by chodorowicz** [comment]
This is great, thank you for that 🙇

Btw. Have you noticed that now TS seems to pick up type even without using generic?

image

**Comment by karol-majewski** [comment]
That's type inference in action. You don't have to provide generic types explicitly when using functions, TypeScript will assume them based on the types of arguments provided. 🎉 It was always like that from the beginning.

**Comment by chodorowicz** [comment]
I didn't realise that, I've somehow thought you always need to be explicit with generics. That's awesome.
I've added you to contributors Hall of Fame 😃 
https://github.com/chodorowicz/ts-debounce/pull/7

**Comment by karol-majewski** [comment]
Cool! 💯 What do you think about overloading `debounce` so it can be used as method decorator?

**Comment by chodorowicz** [comment]
I'm not sure about overloading in the first iteration, but writing a decorator version of debounce sounds like a very good idea. I've found even a flow implementation of that
https://github.com/bvaughn/debounce-decorator/blob/master/source/Debounce.js

**Pull request merged**
